In [4]:
import numpy as np
matrix = np.array([[1,2],
                  [1,2],
                  [1,2]])

In [8]:
type(matrix)

numpy.ndarray

In [9]:
import numpy as np
from scipy import sparse

In [11]:
matrix = np.array([[0,0],
                  [0,1],
                  [3,0]])
matrix_sparse = sparse.csr_matrix(matrix)

In [13]:
print(matrix_sparse)

  (1, 1)	1
  (2, 0)	3


In [14]:
vector = np.array([1,2,3,4,5,6])
matrix = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])

In [15]:
vector[2]

3

In [17]:
matrix[1,2]

6

In [18]:
vector[:]

array([1, 2, 3, 4, 5, 6])

In [19]:
vector[:4]

array([1, 2, 3, 4])

In [20]:
vector[5:]

array([6])

In [21]:
vector[-1]

6

In [22]:
matrix[:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
matrix[:,1:2]

array([[2],
       [5],
       [8]])

In [25]:
matrix = np.array([[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12]])

In [26]:
matrix.shape

(3, 4)

In [28]:
matrix.size

12

In [29]:
matrix.ndim

2

In [30]:
matrix = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])

In [31]:
add_100 = lambda i:i+100
vectorized_add_100 = np.vectorize(add_100)
vectorized_add_100(matrix)

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [32]:
np.max(matrix)

9

In [33]:
np.min(matrix)

1

In [35]:
print(np.max(matrix,axis=0))
print(np.max(matrix,axis=1))

[7 8 9]
[3 6 9]


In [36]:
np.mean(matrix)

5.0

In [37]:
np.var(matrix)

6.666666666666667

In [38]:
np.std(matrix)

2.581988897471611

In [39]:
np.mean(matrix,axis=0)

array([4., 5., 6.])

In [40]:
matrix = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9],
                  [10,11,12]])

In [41]:
matrix.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [42]:
matrix.reshape(-1,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [43]:
matrix.reshape(1,-1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [46]:
print(matrix)
print("========================")
print(matrix.T)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]


In [49]:
print(vector)
print('============')
print(vector.T)

[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [50]:
matrix.flatten()  #similar to matrix.reshape(1,-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [51]:
#Rank of a matrix
np.linalg.matrix_rank(matrix)

2

In [54]:
#Determinant of a matrix
matrix = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
np.linalg.det(matrix)

-9.51619735392994e-16

In [55]:
matrix.diagonal()

array([1, 5, 9])

In [60]:
matrix.diagonal(offset=1)

array([2, 6])

In [57]:
matrix.diagonal(offset=-1)

array([4, 8])

In [62]:
matrix.trace()

15

In [64]:
sum(matrix.diagonal())

15

In [66]:
#Eigenvalues and Eigenvectors
eigenvalues,eigenvectors = np.linalg.eig(matrix)
print(eigenvalues)
print("=================")
print(eigenvectors)

[ 1.61168440e+01 -1.11684397e+00 -9.75918483e-16]
[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


In [68]:
vector_a = np.array([1,2,3])
vector_b = np.array([4,5,6])
np.dot(vector_a,vector_b)

32

In [69]:
vector_a @ vector_b

32

In [70]:
matrix_a = np.array([[1,1,1],
                    [1,1,1],
                    [1,1,2]])

matrix_b = np.array([[1,3,1],
                    [1,3,1],
                    [1,3,8]])
np.add(matrix_a,matrix_b)


array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

In [72]:
np.subtract(matrix_a,matrix_b)

array([[ 0, -2,  0],
       [ 0, -2,  0],
       [ 0, -2, -6]])

In [73]:
np.dot(matrix_a,matrix_b)

array([[ 3,  9, 10],
       [ 3,  9, 10],
       [ 4, 12, 18]])

In [74]:
matrix_a @ matrix_b

array([[ 3,  9, 10],
       [ 3,  9, 10],
       [ 4, 12, 18]])

In [75]:
#inverse of a matrix
np.linalg.inv(matrix)

array([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
       [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
       [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])

### Random Values

In [77]:
np.random.seed(0)
np.random.random(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [80]:
np.random.randint(0,10,3)

array([5, 2, 4])

In [81]:
np.random.normal(0.0,1.0,6)

array([-0.29139398, -0.13309028, -0.1730696 , -1.76165167, -0.08767307,
        1.36687937])

In [82]:
np.random.logistic(0.0,2.0,3)

array([-0.87124279,  3.25867355, -1.34983899])

In [83]:
np.random.uniform(1.0,2.0,3)

array([1.64817187, 1.36824154, 1.95715516])